version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  # docs:
  #   container_name: docs-container
  #   image: node:12
  #   working_dir: /usr/src/favorite-products-api/docs
  #   command: bash -c "yarn add serve && yarn serve"
  #   volumes:
  #     - ./docs/:/usr/src/favorite-products-api/docs/
  #   ports:
  #     - "5000:5000"
  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/src/favorite-products-api
    restart: always
    command: bash -c "yarn install --production && yarn run debug"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/favorite-products
      - PRODUCTS_API_URL=http://challenge-api.luizalabs.com/api
    volumes:
      - ./dist/:/usr/src/favorite-products-api/dist/
      - ./package.json:/usr/src/favorite-products-api/package.json
    ports:
      - "3333:3333"
      - "9222:9222"
    links:
      - mongo